### ISSUE TITLE
请问各个packages的版本

### ISSUE THREAD

**Issue by yuchen202** [diyiiyiii/StyTR-2#10]
已知pillow<=7.2.0，不知道其他的怎么样
另外，AttributeError: 'tuple' object has no attribute 'cpu'怎么办呢

**Comment by Jamie-Cheung** [comment]
> 已知pillow<=7.2.0，不知道其他的怎么样 另外，AttributeError: 'tuple' object has no attribute 'cpu'怎么办呢

把那边注释掉，直接用上面输出的output

**Comment by 2333someone** [comment]
> > 已知pillow<=7.2.0，不知道其他的怎么样 另外，AttributeError: 'tuple' object has no attribute 'cpu'怎么办呢
> 
> 把那边注释掉，直接用上面输出的output

我也是遇到了同样的问题，刚刚才学习python，请问能说一下具体怎么修改吗？

**Comment by Jamie-Cheung** [comment]
for content_path in content_paths:
for style_path in style_paths:
print(content_path)
    content_tf1 = content_transform()
    content = content_tf(Image.open(content_path).convert("RGB"))

    h, w, c = np.shape(content)
    style_tf1 = style_transform(h, w)
    style = style_tf(Image.open(style_path).convert("RGB"))

    style = style.to(device).unsqueeze(0)
    content = content.to(device).unsqueeze(0)

    with torch.no_grad():
        output = network(content, style)
        # output = output.cuda()
        output = output

    output_name = '{:s}/{:s}_stylized_{:s}{:s}'.format(
        output_path, splitext(basename(content_path))[0],
        splitext(basename(style_path))[0], save_ext
    )
    save_image(output[0], output_name)
You can copy this code to replace corresponding code on test.py

**Comment by phhandong** [comment]
I replace the code with yours, but I got the output as this![result](https://user-images.githubusercontent.com/53261018/186422373-0678c37a-8d2d-45ac-97cd-b772c99f0368.jpg)

**Comment by yuchen202** [comment]
收到了，谢谢

**Comment by phhandong** [comment]
&nbsp; 请问您的问题解决了吗？
&nbsp; 我的环境是RTX3090
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; cuda&nbsp;V11.6.124
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; pytorch 1.6
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; cycler&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 0.11.0
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; future&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 0.18.2
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; importlib-resources 5.4.0
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; kiwisolver&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 1.3.1
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; matplotlib&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 3.3.4
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; numpy&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;1.19.5
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Pillow&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 8.4.0
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; pip&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;21.2.2
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; pyparsing&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;3.0.9
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; python-dateutil&nbsp; &nbsp; &nbsp;2.8.2
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; scipy&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;1.5.4
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; setuptools&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 58.0.4
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; six&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;1.16.0
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; torch&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;1.4.0
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; torchvision&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;0.5.0
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; tqdm&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 4.64.0
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; wheel&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;0.37.1
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; zipp&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 3.6.0




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "diyiiyiii/StyTR-2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月24日(星期三) 晚上8:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [diyiiyiii/StyTR-2] 请问各个packages的版本 (Issue #10)





 收到了，谢谢
