### ISSUE TITLE
似乎StyTrans类中的this.embedding并没有实例化

### ISSUE THREAD

**Issue by wangzexi** [diyiiyiii/StyTR-2#11]
作者你好，我在学习您代码时发现，在StyTrans类构造函数中，`this.embedding`看起来是一个类，并没有提供参数实例化，想请教下实例化的参数是什么。

https://github.com/diyiiyiii/StyTR-2/blob/c11ea32913d16dbf2f9a1f82ac077dbf90f143c6/models/StyTR.py#L158

https://github.com/diyiiyiii/StyTR-2/blob/c11ea32913d16dbf2f9a1f82ac077dbf90f143c6/models/StyTR.py#L197

**Comment by charliie-dev** [comment]
u can use github to click on `PatchEmbed`, it will tell u the definition and references of it.

**Comment by charliie-dev** [comment]
also, **i think** the author forgot to put the `()` after `PatchEmbed`, Line 158 should be `self.embedding = PatchEmbed() `

**Comment by wangzexi** [comment]
别关issue呀邓盈盈博士，这代码您不是还没修正呢！
