### ISSUE TITLE
PatchEmbed源码和论文图中好像操作方法好像不太一样

### ISSUE THREAD

**Issue by panda66666666** [diyiiyiii/StyTR-2#13]
作者您好！我有一个问题，你们源码中每一个patch就是将图像输入到卷积之后一个通道维度的张量，但是原论文图中好像是对一张图像的不同区域分块之后得到patch，请问这是为啥

**Comment by diyiiyiii** [comment]
通过这个卷积分块

**Comment by panda66666666** [comment]
> 
用卷积的话每一个patch都会有全局信息，论文示意图中好像每一个patch都是切分的，只是局部信息

**Comment by tweee1234** [comment]
> > 
> 
> 用卷积的话每一个patch都会有全局信息，论文示意图中好像每一个patch都是切分的，只是局部信息

你好，我注意到源码中kernel_size和stride都是patch_size，每次卷积区域没有重合，所以我认为这里的全局信息应该仅限于同一个patch内的，从整幅图像的角度看，每一个独立的patch所生成的新向量包含的仍是局部信息，或许论文示意图所表达的也是这个意思。

**Comment by Chonghuan-Liu** [comment]
> > > 
> > 
> > 
> > 用卷积的话每一个patch都会有全局信息，论文示意图中好像每一个patch都是切分的，只是局部信息
> 
> 你好，我注意到源码中kernel_size和stride都是patch_size，每次卷积区域没有重合，所以我认为这里的全局信息应该仅限于同一个patch内的，从整幅图像的角度看，每一个独立的patch所生成的新向量包含的仍是局部信息，或许论文示意图所表达的也是这个意思。

额，这么理解我不知道啊，不过原文图像画的是原始vit的那种分块取patch，这种取patch的方法我不知道是不是会更好。。。。

**Comment by panda66666666** [comment]
哦哦，又看了一遍是这样的，每一个卷积核只覆盖一小个范围，文章没毛病
