### ISSUE TITLE
Arbitrary output size instead of square

### ISSUE THREAD

**Issue by teyou** [diyiiyiii/StyTR-2#17]
Hi, is there a way to generate output image while keeping the same ratio and resolution as per input content image? It seems currently it only support `square` image.

For example, I have a content image with 1920x1080, a style image with 1000x500 and I would like to have an output image with 1920x1080 as well?

**Comment by zhangyupeng123** [comment]
Could you please tell me how you achieved this ？@teyou

**Comment by teyou** [comment]
> Could you please tell me how you achieved this ？@teyou 

Sorry, I have forgotten. Been too long

**Comment by zhangyupeng123** [comment]
So this means that this code can adjust the size of the generated images, right?

**Comment by zhangyupeng123** [comment]
So this means that this code can adjust the size of the generated images, right? @teyou
