### ISSUE TITLE
实验条件

### ISSUE THREAD

**Issue by Jamie-Cheung** [diyiiyiii/StyTR-2#6]
请问多少G显存是合适的，或者你们用的是什么显卡

**Comment by HolmesShuan** [comment]
FYI.

> Our model is trained on two NVIDIA Tesla P100 GPUs and two NVIDIA GeForce RTX 3090 GPUs.

FP16 seems to be a good option if you encounter OOM.

**Comment by Jamie-Cheung** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    Thank you for your time. I want to know whether your code can be trained on 2*3090. I failed to train it on my computer, Ubuntu18 2*3090. 
        Error:RuntimeError: CUDA out of memory. Tried to allocate 256.00 MiB (GPU 0; 24.00 GiB total capacity; 21.24 GiB already allocated; 210.21 MiB free; 21.30 GiB reserved in total by PyTorch)
    
     
    
        
                    ***@***.***
        
    
 

    在2022年3月12日 ***@***.***> 写道： 



Closed #6.
